### PR TITLE
Diseño

### PR DESCRIPTION
**Pull request by JesiRei333**
feat: notita de fecha
feat: intercambio de botones nav
feat: intercambio de botones recuerdame registro
feat: animación menu temas
feat: responsive temas, fav, vistos
feat: burbuja boton cambiar fondo
feat: escenarios responsive
feat: logros, medallas giran, medalla grande pulsa, boton cerrar
feat: menu usuario animaciones

### CODE REVIEW

**Comment by JesiRei333** [comment]
https://github.com/user-attachments/assets/83811e53-605e-4b80-b579-4c46dd432e88
https://github.com/user-attachments/assets/b4a8077d-8edd-4e18-9503-52c0b9c8386f
https://github.com/user-attachments/assets/7865c2ba-fe5f-4988-8d49-8cbf5aae0fd5
https://github.com/user-attachments/assets/0dbc3fde-14d8-45fb-b98d-90482cd333fa
https://github.com/user-attachments/assets/2e0ed3ae-6035-41b3-b8b1-eeecbb1a5a77
https://github.com/user-attachments/assets/0ca2f0fe-7196-4827-a9c9-830167ce4208
https://github.com/user-attachments/assets/41215348-4e4e-4e46-b1a3-22e86d8e5471

**Comment by JesiRei333** [comment]
https://github.com/user-attachments/assets/687ad63d-3608-4cb4-8da7-425e971f7199

**Comment by JesiRei333** [comment]
https://github.com/user-attachments/assets/5ce86237-f269-414e-a1f3-2893c0b9412b

**Comment by JesiRei333** [comment]
https://github.com/user-attachments/assets/89b055f0-d08a-4a6e-be94-55fd2fa983c3

**Comment by JesiRei333** [comment]
https://github.com/user-attachments/assets/6e4d7925-0d6b-4c54-8af0-56561a89ecc1

**Comment by JesiRei333** [comment]
https://github.com/user-attachments/assets/474527fc-4cac-41ab-924a-374a9cbce09f

**Comment by JesiRei333** [comment]
https://github.com/user-attachments/assets/68ddf827-9937-44e6-85ea-f85ea55d9168

**Comment by JesiRei333** [comment]
https://github.com/user-attachments/assets/002fcbea-1fd1-4feb-b68c-3bba2a951118

**Review by angelaggar — APPROVED** [review]

**Pull request merged**
